# NeuroBridge EDU Frontend - Kubernetes Deployment
# Educational institution optimized with security hardening and performance
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neurobridge-frontend
  namespace: neurobridge-edu
  labels:
    app: neurobridge-edu
    component: frontend
    tier: presentation
    educational-compliance: required
  annotations:
    deployment.kubernetes.io/revision: "1"
    description: "NeuroBridge EDU React Frontend for educational institutions"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: neurobridge-edu
      component: frontend
  template:
    metadata:
      labels:
        app: neurobridge-edu
        component: frontend
        tier: presentation
        educational-compliance: required
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        compliance.io/data-processing: "minimal"
    spec:
      # Security: Service account for educational RBAC
      serviceAccountName: neurobridge-frontend
      
      # Security: Run as non-root user
      securityContext:
        runAsNonRoot: true
        runAsUser: 101  # nginx user
        runAsGroup: 101
        fsGroup: 101
      
      # Educational pod distribution
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values: [frontend]
              topologyKey: kubernetes.io/hostname
      
      containers:
      - name: frontend
        image: neurobridge/frontend:optimized-latest
        imagePullPolicy: Always
        
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        
        # Security: Minimal privileges for static serving
        securityContext:
          runAsNonRoot: true
          runAsUser: 101
          runAsGroup: 101
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
            add: ["CHOWN", "SETGID", "SETUID"]
        
        # Educational environment variables
        env:
        - name: NGINX_ENVSUBST_OUTPUT_DIR
          value: "/tmp/nginx"
        - name: NODE_ENV
          value: "production"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        
        # Resource limits for educational environments
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
            ephemeral-storage: 100Mi
          limits:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 1Gi
        
        # Educational health checks
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        
        startupProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 10
        
        # Volume mounts for writable directories
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-logs
          mountPath: /var/log/nginx
        - name: tmp-nginx
          mountPath: /tmp
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
      
      # Educational volumes
      volumes:
      - name: nginx-cache
        emptyDir:
          sizeLimit: 100Mi
      - name: nginx-logs
        emptyDir:
          sizeLimit: 50Mi
      - name: tmp-nginx
        emptyDir:
          sizeLimit: 50Mi
      - name: nginx-config
        configMap:
          name: nginx-config
          defaultMode: 0644
      
      # Educational restart and DNS policies
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirst
      
      # Image pull secrets for private registries
      imagePullSecrets:
      - name: neurobridge-registry-secret