# NeuroBridge EDU - Persistent Volume Claims
# Educational data storage with compliance and backup requirements
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neurobridge-data
  namespace: neurobridge-edu
  labels:
    app: neurobridge-edu
    component: storage
    data-type: educational
    compliance: ferpa-gdpr
  annotations:
    description: "Educational database storage with FERPA/GDPR compliance"
    backup.io/schedule: "0 2 * * *"  # Daily backup at 2 AM
    backup.io/retention: "2555"      # 7 years retention for educational records
    volume.beta.kubernetes.io/storage-class: "educational-ssd"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: educational-ssd
  resources:
    requests:
      storage: 50Gi  # Educational database storage
  selector:
    matchLabels:
      data-classification: educational
      compliance: ferpa-gdpr

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neurobridge-models
  namespace: neurobridge-edu
  labels:
    app: neurobridge-edu
    component: ml-cache
    data-type: models
  annotations:
    description: "Whisper ML model cache for educational workloads"
    backup.io/schedule: "0 3 * * 0"  # Weekly backup on Sunday at 3 AM
    backup.io/retention: "90"        # 90 days retention for ML models
    volume.beta.kubernetes.io/storage-class: "educational-standard"
spec:
  accessModes:
    - ReadWriteMany  # Share models across backend pods
  storageClassName: educational-standard
  resources:
    requests:
      storage: 20Gi  # Whisper models cache
  selector:
    matchLabels:
      data-type: ml-models
      performance: high-iops

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neurobridge-audit-logs
  namespace: neurobridge-edu
  labels:
    app: neurobridge-edu
    component: audit
    data-type: logs
    compliance: required
  annotations:
    description: "Educational audit logs for compliance monitoring"
    backup.io/schedule: "0 1 * * *"  # Daily backup at 1 AM
    backup.io/retention: "2555"      # 7 years retention for audit trails
    volume.beta.kubernetes.io/storage-class: "educational-logs"
spec:
  accessModes:
    - ReadWriteMany  # Multiple pods can write audit logs
  storageClassName: educational-logs
  resources:
    requests:
      storage: 100Gi  # Audit log storage
  selector:
    matchLabels:
      data-classification: audit
      compliance: ferpa-gdpr