
services:
  # NeuroBridge EDU Frontend (React + Vite)
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: neurobridge-frontend
    ports:
      - "3131:3131"
    environment:
      - VITE_API_BASE_URL=http://localhost:3939
    # No volumes needed for production deployment
    # volumes:
    #   - ./src:/app/src:ro
    #   - ./public:/app/public:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - neurobridge-network

  # NeuroBridge EDU Backend (Python FastAPI)
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: neurobridge-backend
    ports:
      - "3939:3939"
    environment:
      - HOST=0.0.0.0
      - PORT=3939
      - LOG_LEVEL=INFO
      - DATABASE_PATH=/app/data/neurobridge.db
      # OPENAI_API_KEY removed - use Settings UI to add API keys
      - CORS_ORIGINS=http://localhost:3131,http://localhost:3939,http://localhost:8000
      # Local Whisper configuration for CPU deployment
      - LOCAL_WHISPER_ENABLED=true
      - LOCAL_WHISPER_MODEL_SIZE=base
      - LOCAL_WHISPER_DEVICE=cpu
      - TRANSCRIPTION_METHOD=local_first
    volumes:
      - neurobridge-db:/app/data
      - neurobridge-models:/app/.cache  # Persistent model cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3939/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - neurobridge-network

volumes:
  neurobridge-db:
    driver: local
  neurobridge-models:
    driver: local

networks:
  neurobridge-network:
    driver: bridge
    name: neurobridge-network