# NeuroBridge EDU - Educational Backup System
# Comprehensive backup solution for educational institutions with FERPA/GDPR compliance
# Implements 7-year retention for educational records and audit trails

version: '3.8'

services:
  # Educational Backup Controller
  educational-backup-controller:
    image: velero/velero:v1.12.1
    container_name: neurobridge-backup-controller
    
    # Security: Non-root execution
    user: "65534:65534"
    
    # Educational backup configuration
    command:
      - /velero
      - server
      - --default-backup-storage-location=educational-primary
      - --default-volume-snapshot-locations=educational-snapshots
      - --backup-sync-period=1h
      - --fs-backup-timeout=4h
      - --client-qps=100
      - --client-burst=100
      - --log-level=info
    
    # Educational environment variables
    environment:
      # Educational cloud storage configuration
      - AWS_ACCESS_KEY_ID=${BACKUP_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${BACKUP_AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${BACKUP_AWS_REGION}
      
      # Educational compliance settings
      - BACKUP_RETENTION_POLICY=educational-7year
      - COMPLIANCE_MODE=FERPA_GDPR
      - EDUCATIONAL_CLASSIFICATION=true
      
      # Educational monitoring
      - PROMETHEUS_METRICS=true
      - PROMETHEUS_PORT=8085
    
    volumes:
      - backup-config:/config:ro
      - backup-cache:/cache
      - /var/run/docker.sock:/var/run/docker.sock:ro  # For container backups
    
    ports:
      - "127.0.0.1:8085:8085"  # Prometheus metrics
    
    networks:
      - educational-backup
    
    restart: unless-stopped
    
    # Educational health check
    healthcheck:
      test: ["CMD", "/velero", "version", "--client-only"]
      interval: 30s
      timeout: 10s
      retries: 3
    
    # Resource limits for educational environments
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 512M

  # Educational Database Backup Service
  educational-database-backup:
    image: postgres:15-alpine
    container_name: neurobridge-db-backup
    
    # Security: Non-root execution  
    user: "999:999"
    
    # Educational backup environment
    environment:
      - PGPASSWORD=${DATABASE_PASSWORD}
      - BACKUP_SCHEDULE=0 2 * * *  # Daily at 2 AM
      - BACKUP_RETENTION_DAYS=2555  # 7 years for educational records
      - COMPRESSION_ENABLED=true
      - ENCRYPTION_ENABLED=true
      - EDUCATIONAL_COMPLIANCE=true
    
    volumes:
      - database-backups:/backups
      - ./backup/scripts:/scripts:ro
    
    # Educational backup command
    command: |
      sh -c '
      echo "Educational Database Backup Service Starting..."
      while true; do
        echo "$(date): Running educational database backup..."
        
        # Educational backup with compression and encryption
        BACKUP_FILE="/backups/neurobridge-edu-$(date +%Y%m%d_%H%M%S).sql"
        
        pg_dump -h database -U neurobridge -d neurobridge_edu \
          --verbose \
          --no-owner \
          --no-privileges \
          --create \
          --clean > "$BACKUP_FILE"
        
        if [ $$? -eq 0 ]; then
          echo "Educational database backup successful: $BACKUP_FILE"
          
          # Compress for storage efficiency
          gzip "$BACKUP_FILE"
          
          # Educational compliance logging
          echo "$(date): Educational backup completed - FERPA/GDPR compliant" >> /backups/backup-audit.log
          
          # Cleanup old backups (keep 7 years for educational compliance)
          find /backups -name "neurobridge-edu-*.sql.gz" -mtime +2555 -delete
          
          # Sleep until next backup (24 hours)
          sleep 86400
        else
          echo "Educational database backup failed"
          sleep 3600  # Retry in 1 hour on failure
        fi
      done
      '
    
    networks:
      - educational-backup
      - neurobridge-secure
    
    restart: unless-stopped
    
    depends_on:
      - database

  # Educational File Backup Service
  educational-file-backup:
    image: rclone/rclone:1.64
    container_name: neurobridge-file-backup
    
    # Security: Non-root execution
    user: "1000:1000"
    
    # Educational file backup environment
    environment:
      - BACKUP_DESTINATION=${EDUCATIONAL_BACKUP_DESTINATION}
      - BACKUP_SCHEDULE=0 3 * * *  # Daily at 3 AM
      - SYNC_BANDWIDTH_LIMIT=10M  # Educational bandwidth consideration
      - EDUCATIONAL_RETENTION=7y  # 7 years for educational compliance
    
    volumes:
      - neurobridge-data:/data/database:ro
      - neurobridge-models:/data/models:ro
      - audit-logs:/data/audit:ro
      - file-backup-config:/config/rclone:ro
      - file-backup-cache:/cache
    
    # Educational file sync command
    command: |
      sh -c '
      echo "Educational File Backup Service Starting..."
      
      while true; do
        echo "$(date): Running educational file backup sync..."
        
        # Educational data backup with verification
        rclone sync /data/database remote:educational-backups/database \
          --config=/config/rclone/rclone.conf \
          --log-level=INFO \
          --stats=1h \
          --bwlimit=${SYNC_BANDWIDTH_LIMIT} \
          --checksum \
          --exclude="*.tmp" \
          --exclude="*.lock"
        
        # Educational model cache backup
        rclone sync /data/models remote:educational-backups/models \
          --config=/config/rclone/rclone.conf \
          --log-level=INFO \
          --bwlimit=${SYNC_BANDWIDTH_LIMIT} \
          --checksum
        
        # Educational audit logs backup (compliance requirement)
        rclone sync /data/audit remote:educational-backups/audit \
          --config=/config/rclone/rclone.conf \
          --log-level=INFO \
          --bwlimit=${SYNC_BANDWIDTH_LIMIT} \
          --checksum
        
        if [ $$? -eq 0 ]; then
          echo "Educational file backup completed successfully"
          
          # Educational backup verification
          rclone check /data/database remote:educational-backups/database \
            --config=/config/rclone/rclone.conf \
            --one-way
            
          echo "$(date): Educational file backup verified - FERPA/GDPR compliant"
        else
          echo "Educational file backup failed"
        fi
        
        # Sleep for 24 hours
        sleep 86400
      done
      '
    
    networks:
      - educational-backup
    
    restart: unless-stopped

  # Educational Backup Monitoring
  educational-backup-monitor:
    image: prom/node-exporter:v1.7.0
    container_name: neurobridge-backup-monitor
    
    # Security: Non-root execution
    user: "65534:65534"
    
    ports:
      - "127.0.0.1:9101:9100"
    
    # Educational backup monitoring configuration
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.textfile.directory=/var/lib/node_exporter/textfile_collector'
      - '--collector.textfile'
      - '--no-collector.arp'
      - '--no-collector.bcache'
      - '--no-collector.bonding'
    
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - backup-metrics:/var/lib/node_exporter/textfile_collector
    
    networks:
      - educational-backup
    
    restart: unless-stopped

  # Educational Backup Verification Service
  educational-backup-verify:
    image: alpine:3.18
    container_name: neurobridge-backup-verify
    
    # Educational verification environment
    environment:
      - VERIFICATION_SCHEDULE=0 6 * * 0  # Weekly on Sunday at 6 AM
      - EDUCATIONAL_COMPLIANCE_CHECK=true
      - RETENTION_VALIDATION=true
    
    volumes:
      - database-backups:/backups:ro
      - verification-reports:/reports
      - ./backup/scripts:/scripts:ro
    
    # Educational backup verification
    command: |
      sh -c '
      apk add --no-cache postgresql15-client gzip
      
      echo "Educational Backup Verification Service Starting..."
      
      while true; do
        echo "$(date): Running educational backup verification..."
        
        # Find latest backup
        LATEST_BACKUP=$(ls -t /backups/neurobridge-edu-*.sql.gz | head -1)
        
        if [ -n "$LATEST_BACKUP" ]; then
          echo "Verifying educational backup: $LATEST_BACKUP"
          
          # Test backup integrity
          gunzip -t "$LATEST_BACKUP"
          
          if [ $$? -eq 0 ]; then
            echo "Educational backup integrity verified: $LATEST_BACKUP"
            
            # Generate verification report
            REPORT_FILE="/reports/backup-verification-$(date +%Y%m%d).txt"
            cat > "$REPORT_FILE" << EOF
NeuroBridge EDU Backup Verification Report
==========================================
Date: $(date)
Backup File: $LATEST_BACKUP
Backup Size: $(stat -c%s "$LATEST_BACKUP" | numfmt --to=iec)
Integrity Check: PASSED
Educational Compliance: FERPA/GDPR COMPLIANT
Retention Policy: 7 Years (2555 days)

Educational Backup Inventory:
$(ls -la /backups/neurobridge-edu-*.sql.gz)

Total Backups: $(ls /backups/neurobridge-edu-*.sql.gz | wc -l)
Oldest Backup: $(ls -t /backups/neurobridge-edu-*.sql.gz | tail -1)
Total Storage Used: $(du -sh /backups | cut -f1)
EOF
            
            echo "Educational backup verification report generated: $REPORT_FILE"
          else
            echo "Educational backup integrity check failed: $LATEST_BACKUP"
          fi
        else
          echo "No educational backups found for verification"
        fi
        
        # Sleep for 1 week (604800 seconds)
        sleep 604800
      done
      '
    
    networks:
      - educational-backup
    
    restart: unless-stopped

# Educational backup volumes
volumes:
  backup-config:
    driver: local
  backup-cache:
    driver: local
  database-backups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/neurobridge/backups/database
  file-backup-config:
    driver: local
  file-backup-cache:
    driver: local
  backup-metrics:
    driver: local
  verification-reports:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/neurobridge/backup-reports
  
  # Reference to main application volumes
  neurobridge-data:
    external: true
  neurobridge-models:
    external: true
  audit-logs:
    external: true

# Educational backup network
networks:
  educational-backup:
    driver: bridge
    name: neurobridge-backup
    driver_opts:
      com.docker.network.bridge.name: nbr-backup
    ipam:
      config:
        - subnet: 172.23.0.0/24
  
  # Connection to main application network
  neurobridge-secure:
    external: true