# NeuroBridge EDU - Educational Institution Alert Rules
# Prometheus alerting rules optimized for educational workload patterns

groups:
  # Educational Service Availability
  - name: educational_service_availability
    interval: 30s
    rules:
      # Backend service critical for educational continuity
      - alert: EducationalBackendDown
        expr: up{job="neurobridge-backend"} == 0
        for: 30s
        labels:
          severity: critical
          service: backend
          impact: educational_disruption
          compliance: ferpa_gdpr
        annotations:
          summary: "NeuroBridge EDU Backend is down"
          description: "Backend service has been down for {{ $value }} seconds. This affects all educational transcription services."
          educational_impact: "Students cannot access transcription services during lectures"
          remediation: "Check backend pod status, logs, and resource availability"
          runbook_url: "https://docs.neurobridge.edu/runbooks/backend-down"

      # Frontend service availability for student access
      - alert: EducationalFrontendDown
        expr: up{job="neurobridge-frontend"} == 0
        for: 1m
        labels:
          severity: warning
          service: frontend
          impact: student_access
        annotations:
          summary: "NeuroBridge EDU Frontend is down"
          description: "Frontend service unavailable, students cannot access the application"
          educational_impact: "Student web interface unavailable"

  # Educational Performance Monitoring
  - name: educational_performance
    interval: 30s
    rules:
      # Morning lecture rush detection (8-10 AM)
      - alert: MorningLectureRush
        expr: rate(http_requests_total{job="neurobridge-backend"}[5m]) > 10
        for: 2m
        labels:
          severity: info
          pattern: morning_rush
          time_sensitive: true
        annotations:
          summary: "High transcription load detected during lecture hours"
          description: "{{ $value }} requests/second during peak educational hours"
          educational_context: "Likely morning lecture period (8-10 AM)"
          action_needed: "Monitor auto-scaling behavior"

      # Whisper model loading performance
      - alert: WhisperModelLoadingSlow
        expr: whisper_model_load_duration_seconds > 30
        for: 1m
        labels:
          severity: warning
          component: whisper
          impact: transcription_delay
        annotations:
          summary: "Whisper model loading slower than expected"
          description: "Model loading taking {{ $value }} seconds, affecting transcription start time"
          educational_impact: "Delayed transcription start may affect lecture capture"
          optimization: "Consider model pre-loading or faster storage"

      # Educational database response time
      - alert: EducationalDatabaseSlow
        expr: database_query_duration_seconds{quantile="0.95"} > 1.0
        for: 2m
        labels:
          severity: warning
          component: database
          impact: user_experience
        annotations:
          summary: "Educational database queries are slow"
          description: "95th percentile query time is {{ $value }} seconds"
          educational_impact: "Slow API responses affecting student experience"

  # Educational Resource Management
  - name: educational_resources
    interval: 30s
    rules:
      # Educational fair use CPU monitoring
      - alert: EducationalCPUHighUsage
        expr: (100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 85
        for: 3m
        labels:
          severity: warning
          resource: cpu
          impact: performance_degradation
        annotations:
          summary: "High CPU usage on educational infrastructure"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"
          educational_impact: "May affect transcription quality and response times"
          capacity_planning: "Consider adding more nodes during peak hours"

      # Educational memory management
      - alert: EducationalMemoryHighUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
        for: 2m
        labels:
          severity: critical
          resource: memory
          impact: service_instability
        annotations:
          summary: "High memory usage on educational infrastructure"
          description: "Memory usage is {{ $value }}% on {{ $labels.instance }}"
          educational_impact: "Risk of service crashes during peak educational usage"
          immediate_action: "Scale up or restart services with high memory usage"

      # Educational storage monitoring for compliance
      - alert: EducationalStorageLow
        expr: (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"} * 100) < 15
        for: 5m
        labels:
          severity: warning
          resource: storage
          compliance_risk: true
        annotations:
          summary: "Low storage space on educational infrastructure"
          description: "Only {{ $value }}% storage available on {{ $labels.device }}"
          educational_impact: "Risk of losing educational data or audit logs"
          compliance_note: "Ensure adequate storage for FERPA/GDPR retention requirements"

  # Educational Security and Compliance
  - name: educational_security_compliance
    interval: 1m
    rules:
      # Educational API key usage monitoring
      - alert: EducationalAPIKeyUsageHigh
        expr: rate(openai_api_calls_total[5m]) * 60 > 100
        for: 2m
        labels:
          severity: warning
          cost_management: true
          api_usage: excessive
        annotations:
          summary: "High OpenAI API usage in educational environment"
          description: "{{ $value }} API calls per minute, may indicate cost concern"
          educational_budget: "Monitor API costs against educational budget"
          optimization: "Review local Whisper usage to reduce API dependency"

      # Educational authentication issues
      - alert: EducationalAuthenticationFailures
        expr: rate(auth_failures_total[5m]) > 0.1
        for: 1m
        labels:
          severity: warning
          security: authentication
          compliance_concern: true
        annotations:
          summary: "Authentication failures in educational system"
          description: "{{ $value }} authentication failures per second"
          security_impact: "Possible unauthorized access attempts"
          compliance_action: "Review access logs for FERPA/GDPR compliance"

      # Educational audit log monitoring
      - alert: EducationalAuditLogsMissing
        expr: up{job="audit-logs"} == 0
        for: 30s
        labels:
          severity: critical
          compliance: mandatory
          audit: failed
        annotations:
          summary: "Educational audit logs not being collected"
          description: "Audit log collection has failed"
          compliance_risk: "FERPA/GDPR compliance violation risk"
          immediate_action: "Restore audit logging immediately for compliance"

  # Educational Auto-scaling Monitoring
  - name: educational_autoscaling
    interval: 30s
    rules:
      # Educational workload scaling detection
      - alert: EducationalScalingEvent
        expr: changes(kube_deployment_status_replicas[5m]) > 0
        for: 0s
        labels:
          severity: info
          scaling: auto
          educational_pattern: detected
        annotations:
          summary: "Educational workload auto-scaling event"
          description: "Pod count changed to {{ $value }} replicas for {{ $labels.deployment }}"
          educational_context: "Scaling due to educational workload patterns"
          monitoring: "Verify scaling aligns with lecture schedules"

      # Educational capacity limits
      - alert: EducationalCapacityLimit
        expr: kube_deployment_status_replicas >= kube_deployment_spec_replicas
        for: 2m
        labels:
          severity: warning
          capacity: limit_reached
          scaling: blocked
        annotations:
          summary: "Educational deployment at maximum capacity"
          description: "{{ $labels.deployment }} reached maximum {{ $value }} replicas"
          educational_impact: "Cannot scale further during peak educational demand"
          capacity_planning: "Consider increasing max replicas for educational peak periods"