# NeuroBridge EDU - Security Hardened Docker Compose
# Educational institution grade deployment with CIS Docker Benchmark compliance
# Implements FERPA/GDPR compliant container security for educational workloads

version: '3.8'

services:
  # Frontend Service - Security Hardened
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend.optimized
    container_name: neurobridge-frontend-secure
    
    # Security: Use optimized port mapping
    ports:
      - "3131:8080"
    
    # Security: Non-root execution and read-only filesystem
    user: "101:101"  # nginx user
    read_only: true
    
    # Security: Minimal required capabilities
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    
    # Security: No privilege escalation
    security_opt:
      - no-new-privileges:true
      - seccomp:docker/security/seccomp-frontend.json
      - apparmor:docker-default
    
    # Security: Resource limits for educational fair use
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Educational environment variables
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/tmp/nginx
      - VITE_API_BASE_URL=http://localhost:3939
    
    # Security: Temporary filesystems for writable areas
    tmpfs:
      - /tmp:size=100M,noexec,nosuid,nodev
      - /var/cache/nginx:size=50M,noexec,nosuid,nodev
      - /var/log/nginx:size=50M,noexec,nosuid,nodev
      - /var/run:size=10M,noexec,nosuid,nodev
    
    # Security: No host filesystem access
    volumes:
      - nginx-cache:/var/cache/nginx:ro
      - nginx-logs:/var/log/nginx
    
    depends_on:
      - backend
    
    restart: unless-stopped
    
    # Security: Health check with timeout
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    
    networks:
      - neurobridge-secure
      - neurobridge-frontend-only

  # Backend Service - Security Hardened
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend.optimized
    container_name: neurobridge-backend-secure
    
    ports:
      - "127.0.0.1:3939:3939"  # Bind to localhost only for security
    
    # Security: Non-root execution
    user: "1001:1001"  # neurobridge user
    read_only: true
    
    # Security: Minimal capabilities
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE  # For file access
      - CHOWN        # For file ownership
    
    # Security: Enhanced protections
    security_opt:
      - no-new-privileges:true
      - seccomp:docker/security/seccomp-backend.json
      - apparmor:docker-default
    
    # Educational resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    
    # Educational and security environment
    environment:
      - HOST=0.0.0.0
      - PORT=3939
      - LOG_LEVEL=INFO
      - DATABASE_PATH=/app/data/neurobridge.db
      - CORS_ORIGINS=http://localhost:3131
      # Security: Disable external telemetry
      - HF_HUB_DISABLE_TELEMETRY=1
      - HF_HUB_DISABLE_PROGRESS_BARS=1
      # Educational defaults
      - LOCAL_WHISPER_ENABLED=true
      - LOCAL_WHISPER_MODEL_SIZE=base
      - TRANSCRIPTION_METHOD=local_first
      # Security: API key from secrets
      - OPENAI_API_KEY_FILE=/run/secrets/openai_api_key
    
    # Security: Secrets management
    secrets:
      - openai_api_key
      - jwt_secret
    
    # Security: Controlled filesystem access
    tmpfs:
      - /tmp:size=500M,noexec,nosuid,nodev
      - /app/logs:size=100M,noexec,nosuid,nodev
    
    volumes:
      # Educational data persistence with security
      - neurobridge-db:/app/data:Z
      - neurobridge-models:/app/.cache:Z
      # Audit logging
      - audit-logs:/var/log/audit:Z
    
    restart: unless-stopped
    
    # Educational health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3939/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    networks:
      - neurobridge-secure

# Security: External secrets management
secrets:
  openai_api_key:
    external: true
    name: neurobridge_openai_key
  jwt_secret:
    external: true
    name: neurobridge_jwt_secret

# Security: Named volumes with access controls
volumes:
  neurobridge-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/neurobridge/data
  neurobridge-models:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/neurobridge/models
  nginx-cache:
    driver: local
  nginx-logs:
    driver: local
  audit-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/log/neurobridge/audit

# Security: Network segmentation for educational compliance
networks:
  # Internal network for backend services
  neurobridge-secure:
    driver: bridge
    internal: true
    name: neurobridge-secure
    driver_opts:
      com.docker.network.bridge.name: nbr-secure
      com.docker.network.bridge.enable_ip_masquerade: "false"
    ipam:
      config:
        - subnet: 172.20.0.0/24
  
  # Frontend-only network for public access
  neurobridge-frontend-only:
    driver: bridge
    name: neurobridge-frontend
    driver_opts:
      com.docker.network.bridge.name: nbr-frontend
    ipam:
      config:
        - subnet: 172.21.0.0/24