# NeuroBridge EDU - AlertManager Configuration
# Educational institution alerting with compliance-focused notifications

global:
  # Educational SMTP configuration
  smtp_smarthost: 'smtp.institution.edu:587'
  smtp_from: 'neurobridge-alerts@institution.edu'
  smtp_auth_username: 'neurobridge-alerts@institution.edu'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true
  
  # Educational notification settings
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
    enable_http2: true

# Educational alert routing
route:
  group_by: ['alertname', 'severity', 'service']
  group_wait: 30s       # Wait before sending first alert
  group_interval: 5m    # Wait between subsequent alerts
  repeat_interval: 12h  # Wait before repeating resolved alerts
  receiver: 'educational-default'
  
  # Educational routing tree
  routes:
    # Critical educational service alerts
    - match:
        severity: critical
      receiver: 'educational-critical'
      group_wait: 10s
      group_interval: 2m
      repeat_interval: 30m
      continue: true
      
    # Educational compliance alerts
    - match:
        compliance: ferpa_gdpr
      receiver: 'educational-compliance'
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 6h
      continue: true
      
    # Educational security alerts
    - match_re:
        alertname: '.*[Ss]ecurity.*|.*[Aa]uth.*'
      receiver: 'educational-security'
      group_wait: 5s
      group_interval: 1m
      repeat_interval: 4h
      
    # Educational performance alerts
    - match:
        severity: warning
      receiver: 'educational-performance'
      group_wait: 2m
      group_interval: 10m
      repeat_interval: 4h
      
    # Educational info alerts (scaling, etc.)
    - match:
        severity: info
      receiver: 'educational-info'
      group_wait: 5m
      group_interval: 1h
      repeat_interval: 24h

# Educational notification inhibition rules
inhibit_rules:
  # Inhibit warning alerts when critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service', 'instance']
    
  # Inhibit performance alerts during known maintenance
  - source_match:
      maintenance: 'scheduled'
    target_match_re:
      alertname: '.*Performance.*|.*Slow.*'
    equal: ['instance']

# Educational alert receivers
receivers:
  # Default educational receiver
  - name: 'educational-default'
    email_configs:
      - to: 'it-operations@institution.edu'
        subject: '[NeuroBridge EDU] {{ .GroupLabels.alertname }} - {{ .Status | title }}'
        body: |
          {{ range .Alerts }}
          **Educational Alert**: {{ .Annotations.summary }}
          
          **Educational Impact**: {{ .Annotations.educational_impact }}
          
          **Description**: {{ .Annotations.description }}
          
          **Severity**: {{ .Labels.severity }}
          **Service**: {{ .Labels.service }}
          **Instance**: {{ .Labels.instance }}
          
          **Time**: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          
          {{ if .Annotations.remediation }}**Remediation**: {{ .Annotations.remediation }}{{ end }}
          {{ if .Annotations.runbook_url }}**Runbook**: {{ .Annotations.runbook_url }}{{ end }}
          {{ end }}
        headers:
          Priority: 'normal'
          X-Educational-System: 'NeuroBridge EDU'
          
  # Critical educational alerts
  - name: 'educational-critical'
    email_configs:
      - to: 'it-emergency@institution.edu, neurobridge-oncall@institution.edu'
        subject: '🚨 [CRITICAL] NeuroBridge EDU: {{ .GroupLabels.alertname }}'
        body: |
          **CRITICAL EDUCATIONAL SERVICE ALERT**
          
          {{ range .Alerts }}
          **Summary**: {{ .Annotations.summary }}
          **Educational Impact**: {{ .Annotations.educational_impact }}
          **Students Affected**: Potentially all active users
          
          **Technical Details**:
          - Service: {{ .Labels.service }}
          - Instance: {{ .Labels.instance }}
          - Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          - Duration: {{ .StartsAt | duration }}
          
          **Immediate Actions Required**:
          {{ if .Annotations.immediate_action }}{{ .Annotations.immediate_action }}{{ end }}
          
          **Runbook**: {{ .Annotations.runbook_url }}
          {{ end }}
        headers:
          Priority: 'high'
          X-Educational-Emergency: 'true'
    
    # Critical alerts also go to Slack
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#neurobridge-alerts'
        title: '🚨 Critical Educational Service Alert'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          
          Educational Impact: {{ .Annotations.educational_impact }}
          Service: `{{ .Labels.service }}`
          {{ if .Annotations.runbook_url }}[View Runbook]({{ .Annotations.runbook_url }}){{ end }}
          {{ end }}
        send_resolved: true
        
  # Educational compliance alerts
  - name: 'educational-compliance'
    email_configs:
      - to: 'compliance-officer@institution.edu, privacy-officer@institution.edu'
        subject: '[COMPLIANCE] NeuroBridge EDU: {{ .GroupLabels.alertname }}'
        body: |
          **EDUCATIONAL COMPLIANCE ALERT**
          
          {{ range .Alerts }}
          **Compliance Issue**: {{ .Annotations.summary }}
          **Compliance Risk**: {{ .Annotations.compliance_risk }}
          **Regulatory Framework**: {{ .Labels.compliance }}
          
          **Details**:
          {{ .Annotations.description }}
          
          **Required Actions**:
          {{ if .Annotations.compliance_action }}{{ .Annotations.compliance_action }}{{ end }}
          
          **Documentation Required**: Yes - for FERPA/GDPR audit trail
          **Time**: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
        headers:
          Priority: 'high'
          X-Compliance-Alert: 'FERPA-GDPR'
          
  # Educational security alerts
  - name: 'educational-security'
    email_configs:
      - to: 'security-team@institution.edu, it-security@institution.edu'
        subject: '[SECURITY] NeuroBridge EDU: {{ .GroupLabels.alertname }}'
        body: |
          **EDUCATIONAL SECURITY ALERT**
          
          {{ range .Alerts }}
          **Security Issue**: {{ .Annotations.summary }}
          **Security Impact**: {{ .Annotations.security_impact }}
          
          **Technical Details**:
          {{ .Annotations.description }}
          
          **Affected System**: {{ .Labels.instance }}
          **Time**: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          
          **Immediate Investigation Required**
          {{ if .Annotations.compliance_action }}
          **Compliance Note**: {{ .Annotations.compliance_action }}
          {{ end }}
          {{ end }}
        headers:
          Priority: 'high'
          X-Security-Alert: 'Educational-System'
          
  # Educational performance alerts
  - name: 'educational-performance'
    email_configs:
      - to: 'neurobridge-team@institution.edu'
        subject: '[PERFORMANCE] NeuroBridge EDU: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          **Performance Alert**: {{ .Annotations.summary }}
          **Educational Impact**: {{ .Annotations.educational_impact }}
          
          **Metrics**: {{ .Annotations.description }}
          **Service**: {{ .Labels.service }}
          
          {{ if .Annotations.optimization }}**Optimization**: {{ .Annotations.optimization }}{{ end }}
          {{ if .Annotations.capacity_planning }}**Capacity Planning**: {{ .Annotations.capacity_planning }}{{ end }}
          {{ end }}
        headers:
          Priority: 'normal'
          
  # Educational info alerts
  - name: 'educational-info'
    email_configs:
      - to: 'neurobridge-monitoring@institution.edu'
        subject: '[INFO] NeuroBridge EDU: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          **Information**: {{ .Annotations.summary }}
          {{ if .Annotations.educational_context }}**Context**: {{ .Annotations.educational_context }}{{ end }}
          
          **Details**: {{ .Annotations.description }}
          {{ if .Annotations.monitoring }}**Monitoring**: {{ .Annotations.monitoring }}{{ end }}
          {{ end }}
        headers:
          Priority: 'low'

# Educational templates
templates:
  - '/etc/alertmanager/templates/*.tmpl'