# NeuroBridge EDU - Monitoring Infrastructure
# Educational institution observability with Prometheus, Grafana, AlertManager
# Implements educational usage analytics and compliance monitoring

version: '3.8'

services:
  # Prometheus - Educational Metrics Collection
  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: neurobridge-prometheus
    
    # Security: Non-root execution
    user: "65534:65534"
    
    ports:
      - "127.0.0.1:9090:9090"  # Bind to localhost for security
    
    # Educational monitoring configuration
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=90d'  # 90 days for educational analytics
      - '--storage.tsdb.retention.size=20GB'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--web.external-url=http://localhost:9090'
      - '--log.level=info'
      - '--query.max-concurrency=10'  # Limit for educational resource usage
    
    # Educational configuration and data volumes
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/rules/:/etc/prometheus/rules/:ro
      - prometheus-data:/prometheus
    
    # Resource limits for educational environments
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    
    restart: unless-stopped
    
    networks:
      - neurobridge-monitoring
    
    # Educational health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Grafana - Educational Dashboards
  grafana:
    image: grafana/grafana:10.2.2
    container_name: neurobridge-grafana
    
    # Security: Non-root execution
    user: "472:0"
    
    ports:
      - "127.0.0.1:3000:3000"  # Bind to localhost for security
    
    # Educational environment configuration
    environment:
      # Security settings for educational institutions
      - GF_SECURITY_ADMIN_PASSWORD=EduAdmin2024!
      - GF_SECURITY_SECRET_KEY=${GRAFANA_SECRET_KEY}
      - GF_SECURITY_DISABLE_GRAVATAR=true
      
      # Educational branding and UI
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      
      # Educational compliance settings
      - GF_LOG_LEVEL=info
      - GF_LOG_MODE=console,file
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Viewer
      
      # Educational data source settings
      - GF_DATABASE_TYPE=sqlite3
      - GF_DATABASE_PATH=/var/lib/grafana/grafana.db
      
      # Educational authentication (can integrate with LDAP)
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_BASIC_ENABLED=true
      
      # Educational session settings
      - GF_SESSION_LIFE_TIME=86400  # 24 hours for educational sessions
    
    # Educational configuration and data persistence
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    
    # Resource limits for educational environments
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 512M
    
    restart: unless-stopped
    
    networks:
      - neurobridge-monitoring
    
    depends_on:
      - prometheus
    
    # Educational health check
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # AlertManager - Educational Alerting
  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: neurobridge-alertmanager
    
    # Security: Non-root execution
    user: "65534:65534"
    
    ports:
      - "127.0.0.1:9093:9093"  # Bind to localhost for security
    
    # Educational alerting configuration
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
      - '--log.level=info'
      - '--cluster.listen-address='  # Disable clustering for educational setup
    
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager-data:/alertmanager
    
    # Resource limits for educational environments
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    
    restart: unless-stopped
    
    networks:
      - neurobridge-monitoring
    
    # Educational health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9093/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Node Exporter - Educational System Metrics
  node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: neurobridge-node-exporter
    
    # Security: Non-root execution
    user: "65534:65534"
    
    ports:
      - "127.0.0.1:9100:9100"
    
    # Educational system monitoring configuration
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.textfile.directory=/var/lib/node_exporter/textfile_collector'
      - '--no-collector.arp'
      - '--no-collector.bcache'
      - '--no-collector.bonding'
      - '--no-collector.btrfs'
      - '--no-collector.infiniband'
      - '--no-collector.ipvs'
      - '--no-collector.mdadm'
      - '--no-collector.nfs'
      - '--no-collector.nfsd'
      - '--no-collector.powersupplyclass'
      - '--no-collector.rapl'
      - '--no-collector.zfs'
    
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - node-exporter-data:/var/lib/node_exporter:rw
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    
    restart: unless-stopped
    
    networks:
      - neurobridge-monitoring
    
    # Educational health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9100/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

# Educational monitoring volumes
volumes:
  prometheus-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/neurobridge/prometheus
  grafana-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/neurobridge/grafana
  alertmanager-data:
    driver: local
  node-exporter-data:
    driver: local

# Educational monitoring network
networks:
  neurobridge-monitoring:
    driver: bridge
    name: neurobridge-monitoring
    driver_opts:
      com.docker.network.bridge.name: nbr-monitoring
    ipam:
      config:
        - subnet: 172.22.0.0/24